### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by bmstefanski** [Body-Guard-BOT/Body-Guard-BOT#6]
Proponuję dodanie [travisa](https://travis-ci.org/) lub innego CI.

**Comment by Superbizons** [comment]
Witam, propozycja zostanie rozpatrzona w okresie nie przekraczającym 5 dni roboczych, po którym zostanie udzielona odpowiedź. 

Dziękuje za propozycję
Zespół Body Guard BOT

**Comment by Superbizons** [comment]
Ponownie witam, przy czym chciałbym poinformować, iż propozycja została zaakceptowana przez nasz zespół i od tej pory zaczniemy używać travisa. 

Zespół Body Guard BOT
